<template>
  <div class="mt-24 mb-32 bg-black">
    <Particles />
    <div
      class="bg-white/90 container mx-auto p-6 md:p-16 w-full min-h-screen rounded-2xl"
    >
      <div class="prose max-w-none text-black">
        <div class="text-center text-5xl font-extrabold">ABOUT US</div>
        <div class="mt-8">
          <div class="font-extrabold">Our Journey</div>
          <p>
            Welcome to [Your Company Name], where our passion for innovation
            meets the world of app development. Founded in [Year], our mission
            has been to create impactful Android apps that enrich lives and
            empower businesses. With a team that combines seasoned expertise and
            fresh talent, we've carved out a niche for ourselves in the bustling
            digital landscape.
          </p>
          <div class="font-extrabold">Our Philosophy</div>
          <p>
            We believe in more than just developing apps. We believe in creating
            experiences that resonate. Our philosophy is simple: understand the
            client, understand the user. It's this empathetic approach that
            allows us to design apps that not only meet needs but also delight
            users.
          </p>
          <div class="font-extrabold">Our Team</div>
          <p>
            At the heart of [Your Company Name] is a diverse team of dreamers
            and doers. Designers, developers, and strategists, united by a
            shared love for code and design. We're a tight-knit group that
            functions like a well-oiled machine, with each of us bringing our
            unique skills and personalities to the table.
          </p>
          <div class="font-extrabold">Our Approach</div>
          <p>
            Our approach is collaborative, transparent, and agile. We integrate
            our clients into every step of the development process, ensuring
            that each app is a true reflection of their vision. We pride
            ourselves on our ability to adapt, learn, and stay ahead of the
            curve in a constantly evolving tech world.
          </p>
          <div class="font-extrabold">Our Commitment</div>
          <p>
            To our clients, we promise unwavering commitment to quality and
            innovation. To our users, we promise engaging apps that make life a
            little easier, and a lot more exciting. And to ourselves, we promise
            to never stop learning, exploring, and pushing the boundaries of
            what's possible.
          </p>
          <div class="font-extrabold">Join Us</div>
          <p>
            Whether you're looking to develop an app, join our team, or simply
            learn more about what we do, we're always here to chat. Connect with
            us, and let's make something amazing together.
          </p>
          <hr class="border-[1px] border-top border-black mx-16" />
          <p class="text-center italic font-bold">
            ** The above text is simply a placeholder text generated by our
            favorite Chat GPT. **
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup></script>
