<template>
  <div class="mt-24 mb-32 px-5">
    <Particles />
    <div
      class="bg-white/90 container mx-auto p-6 md:p-16 w-full min-h-screen rounded-2xl"
    >
      <div class="prose max-w-none text-black">
        <h1 class="text-center text-5xl font-extrabold">CONTACT US</h1>
        <div class="mt-8">
          <h2>Get in Touch with [Your Company Name]</h2>
          <p>
            We're here to help and answer any question you might have. We look
            forward to hearing from you!
          </p>
          <h2>Email Us:</h2>
          <p>
            For general inquiries, reach out to us at [email@example.com]. For
            support, please email [support@example.com].
          </p>
          <h2>Call Us:</h2>
          <p>Speak directly with our team at [Phone Number].</p>
          <h2>Visit Us:</h2>
          <p>[Your Company Address]</p>
          <div>
            <iframe
              class="w-full"
              title="Google Map Location"
              src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d381.2755515702916!2d-102.88425447510082!3d30.893970832216954!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sin!4v1706344169721!5m2!1sen!2sin"
              width="100%"
              height="450"
              style="border: 0"
              allowfullscreen=""
              loading="async"
              referrerpolicy="no-referrer-when-downgrade"
            ></iframe>
          </div>
          <h2>Business Hours:</h2>
          <ul>
            <li>Monday to Friday - 9:00 AM to 5:00 PM</li>
            <li>Saturday - 10:00 AM to 3:00 PM</li>
            <li>Sunday - Closed</li>
          </ul>
          <h2>Send Us a Message:</h2>
          <p>
            Send a message to us by filling out the
            <NuxtLink to="/#contact">form at home page</NuxtLink>, and we'll get
            back to you as soon as possible.
          </p>
          <hr class="border-[1px] border-top border-black mx-16" />
          <p class="text-center italic font-bold">
            ** The above text is simply a placeholder text generated by our
            favorite Chat GPT. **
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
defineOgImageComponent("NuxtSeo");

useSchemaOrg([
  defineBreadcrumb({
    itemListElement: [
      { name: "Home", item: "/" },
      { name: "Contact Us", item: "/contact" },
    ],
  }),
]);

useSeoMeta({
  title: "Contact",
  description: "Contact Us",
});
</script>
