<template>
  <div class="mt-24 mb-32">
    <Particles />
    <div
      class="bg-white/95 container mx-auto p-6 md:p-16 w-full min-h-screen rounded-2xl"
    >
      <div class="prose max-w-none text-black">
        <h1 class="text-center text-5xl font-extrabold">PRIVACY POLICY</h1>
        <div class="mt-8">
          <p>
            At [Your Company Name], accessible from [Your Company Website], one
            of our main priorities is the privacy of our visitors. This Privacy
            Policy document contains types of information that is collected and
            recorded by [Your Company Name] and how we use it.
          </p>
          <h2>Information We Collect</h2>
          <p>
            The personal information that you are asked to provide, and the
            reasons why you are asked to provide it, will be made clear to you
            at the point we ask you to provide your personal information.
          </p>
          <p>
            If you contact us directly, we may receive additional information
            about you such as your name, email address, phone number, the
            contents of the message and/or attachments you may send us, and any
            other information you may choose to provide.
          </p>
          <h2>How We Use Your Information</h2>
          <p>
            We use the information we collect in various ways, including to:
          </p>
          <ul>
            <li>Provide, operate, and maintain our website</li>
            <li>Improve, personalize, and expand our website</li>
            <li>Understand and analyze how you use our website</li>
            <li>Develop new products, services, features, and functionality</li>
            <li>
              Communicate with you, either directly or through one of our
              partners, including for customer service, to provide you with
              updates and other information relating to the website, and for
              marketing and promotional purposes
            </li>
            <li>Send you emails</li>
            <li>Find and prevent fraud</li>
          </ul>
          <hr class="border-[1px] border-top border-black mx-16" />
          <p class="text-center italic font-bold">
            ** The above text is simply a placeholder text generated by our
            favorite Chat GPT. **
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
defineOgImageComponent("NuxtSeo");

useSeoMeta({
  title: "Privacy Policy",
  description: "Privacy and Policy",
});
</script>
