<template>
  <div class="mt-24 mb-32">
    <Particles />
    <div
      class="bg-white/95 container mx-auto p-16 w-full min-h-screen rounded-2xl"
    >
      <div class="prose max-w-none text-black">
        <div class="text-center text-5xl font-extrabold">PRIVACY POLICY</div>
        <div class="mt-8">
          <p>
            At [Your Company Name], accessible from [Your Company Website], one
            of our main priorities is the privacy of our visitors. This Privacy
            Policy document contains types of information that is collected and
            recorded by [Your Company Name] and how we use it.
          </p>
          <h3 class="font-extrabold">Our Philosophy</h3>
          <p>
            We believe in more than just developing apps. We believe in creating
            experiences that resonate. Our philosophy is simple: understand the
            client, understand the user. It's this empathetic approach that
            allows us to design apps that not only meet needs but also delight
            users.
          </p>
          <h3 class="font-extrabold">Our Team</h3>
          <p>
            At the heart of [Your Company Name] is a diverse team of dreamers
            and doers. Designers, developers, and strategists, united by a
            shared love for code and design. We're a tight-knit group that
            functions like a well-oiled machine, with each of us bringing our
            unique skills and personalities to the table.
          </p>
          <h3 class="font-extrabold">Our Approach</h3>
          <p>
            Our approach is collaborative, transparent, and agile. We integrate
            our clients into every step of the development process, ensuring
            that each app is a true reflection of their vision. We pride
            ourselves on our ability to adapt, learn, and stay ahead of the
            curve in a constantly evolving tech world.
          </p>
          <h3 class="font-extrabold">Our Commitment</h3>
          <p>
            To our clients, we promise unwavering commitment to quality and
            innovation. To our users, we promise engaging apps that make life a
            little easier, and a lot more exciting. And to ourselves, we promise
            to never stop learning, exploring, and pushing the boundaries of
            what's possible.
          </p>
          <h3 class="font-extrabold">Join Us</h3>
          <p>
            Whether you're looking to develop an app, join our team, or simply
            learn more about what we do, we're always here to chat. Connect with
            us, and let's make something amazing together.
          </p>
          <hr class="border-[1px] border-top border-black mx-16" />
          <p class="text-center italic font-bold">
            ** The above text is simply a placeholder text generated by our
            favorite Chat GPT. **
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup></script>
